[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.92.1"
  HUGO_THEME = "agico-hugo"
  HUGO_BASEURL = "/"